### ISSUE TITLE
VirtualChannelCS example in AppStream 2.0

### ISSUE THREAD

**Issue by wenjunche** [aws-samples/dcv-extension-sdk-samples#4]
Hello

I am trying to run the example in AppStream 2.0 and need some help.   Here is what I have done so far:

1. build the example and bundle all binaries, including DcvExtensionVirtualChannelsCS.exe, and a manifest.json, to build a AppStream image.
2. add HKEY_LOCAL_MACHINE\SOFTWARE\Amazon\DCV Registry key pointing to the manifest.json for the image
3. add HKEY_USERS\S-1-5-18\Software\GSettings\com\nicesoftware\dcv\extensions/load-policy=all Registry value for the image

When I log in from AppStream 2.0 client,  I can see DcvExtensionVirtualChannelsCS running in TaskManager and log files are being created by DcvExtensionVirtualChannelsCS in C:/Temp folder with the following content:

~~~
Created
DCV Extension Virtual Channels C#
Requesting DCV info
Sending 'GetDcvInfoRequest' with id '1' to DCV client
~~~

Based on the source code,  `GetDcvInfoAsync`  does not return ?

I am running AppStream 2.0 on Windows server 2019 and AppStream client on Windows 11.

Any insight would be greatly appreciated.   Please feel free to ask for more information

**Comment by gundarev** [comment]
The issue was caused by outdated nuget dependicies

**Comment by wenjunche** [comment]
Thank you for the response.   Just FYI:  I pulled the latest main branch and got build errors, which are fixed after I upgraded Google.Protobuf from 3.27.2 to 3.27.3.   Now the sample code works with AppStream.

Thanks again
